language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - gdal-bin
      - python-gdal
      - libgdal1h
  postgresql: "9.4"
services:
  - postgresql
virtualenv:
  system_site_packages: true
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost:5432/test_youthexplorer
  matrix:
    - WAZI_PROFILE=census
    - WAZI_PROFILE=youth DEFAULT_GEO_VERSION=2011
install:
  - sed 's/GDAL==1.11.0/GDAL==1.10.1/' -i requirements.txt
  - pip install -r requirements.txt
script:
  - psql -c 'create database test_youthexplorer;' -U postgres
  - python manage.py migrate
  - "for f in sql/$WAZI_PROFILE/*.sql; do cat $f | psql -U postgres test_youthexplorer; done"
  - python manage.py loaddata fixtures/$WAZI_PROFILE/wazimap_django_models.json --verbosity 0
  - python manage.py test --keepdb --nomigrations
